version: "3"

services:
  mysql:
    image: "mysql:5.7.31"
    environment:
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_DATABASE: isuumo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      LANG: "C.UTF-8"
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  mysql2:
    image: "mysql:5.7.31"
    environment:
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_DATABASE: isuumo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      LANG: "C.UTF-8"
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
